### ISSUE TITLE
Subtitle/Audio selected doesn't change

### ISSUE THREAD

**Issue by ItzNuggetz** [rhenwinch/Flixclusive#102]
### Steps to reproduce

1. Subtitles selected doesn't change in the middle of the show or at the beginning for that matter. 
2. Subtitles used to change in the previous pre - releases but now it doesn't change or show at all. 
![Screenshot_20240706_131038](https://github.com/rhenwinch/Flixclusive/assets/166253246/1c1f406e-f389-4ca0-8e38-3b4bcf2876f8)

### Expected behavior

Subtitles when checked and selected as the votes go should show up

### Actual behavior

Nothing shows up or selected subtitles change. 

### Flixclusive version

2.0.0 - 183f8a4

### Android version

Android 13

### Device

Honor 90

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the **[latest version](https://github.com/rhenwinch/Flixclusive/releases/latest)**.

**Comment by ItzNuggetz** [comment]
This is EP 2 from the boys season 1

**Comment by rhenwinch** [comment]
Ill get back to this by next week, hope thats fine
