### ISSUE TITLE
Watch time progress not saving after "PlaybackException"

### ISSUE THREAD

**Issue by basil222** [rhenwinch/Flixclusive#103]
### Steps to reproduce

1.Start a video
2.If PlaybackException [2004] : source error happens and you get out of the video
3.Re-open the video and the video loades back to the previous checkpoint of the watch time and not where the source error happend 

### Expected behavior

Watch time progress should save after source errors.

### Actual behavior

Watch time progress not saving after source errors.

### Flixclusive version

Latest pre-release 

### Android version

Android 14

### Device

Samsung s22

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the **[latest version](https://github.com/rhenwinch/Flixclusive/releases/latest)**.

**Comment by rhenwinch** [comment]
This also happens when changing provider/server. Will fix now
