### ISSUE TITLE
Cant scroll down on privacy notice Android 14

### ISSUE THREAD

**Issue by casinoboy1** [rhenwinch/Flixclusive#109]
### Steps to reproduce

1. Android 14/Android 9.1.1
2. Open app
3. Cant scroll down on privacy notice

### Expected behavior

Should be able to scroll down and accept terms that may be at the bottom.

### Actual behavior

Whenever you try to scroll down on the Privacy Notice to I guess accept what's at the bottom, you can't. Nothing moves when you try and swipe to get to the bottom. Same thing happens on nvidia shield pro.

### Flixclusive version

2.0.0 and 1.4.0

### Android version

Android 14/Android 9.1.1

### Device

Galaxy A54/Nvidia Shield

### Acknowledgements

- [X] I am ***fully confident*** that this issue is related solely to the app and not to any provider.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the **[pre-release version](https://github.com/rhenwinch/Flixclusive/releases/tag/pre-release)**.

**Comment by rhenwinch** [comment]
Are you on TV UI mode? Bc if you are my UI sucks on wider screens, I puke on it. Gotta wait til the UI enhancement update, check discord ❤️

**Comment by casinoboy1** [comment]
Even on android 14 on the phone it's the same thing. I havent even had a chance to use the app because I cant get past Privacy Notice screen. Thanks for replying too and where can I find the discord link?

**Comment by rhenwinch** [comment]
Hi, sorry the update for this might be delayed. Apologies

**Comment by rhenwinch** [comment]
Will push an update for this, hopefully this will get fixed on that commit.

**Comment by casinoboy1** [comment]
Thanks a lot for taking the time to do this. I appreciate and will check it out to see.
