### ISSUE TITLE
Picture-in-picture (PiP) mode

### ISSUE THREAD

**Issue by back2Lobby** [rhenwinch/Flixclusive#115]
### Describe your suggested feature

A Picture-in-picture (PiP) mode for videos would be a very nice addition to the features that this app offers.

**Comment by rhenwinch** [comment]
Wdym for videos? The app has a PiP mode

**Comment by back2Lobby** [comment]
omg I was looking for the button, never tried to switch to other app while the video is playing, mb sorry 😅.
