### ISSUE TITLE
Support for Non PIP devices

### ISSUE THREAD

**Issue by freakynuell** [rhenwinch/Flixclusive#118]
### Steps to reproduce

Tries to play any movie
Movie plays for 0.2s 
crashes out with log details

### Expected behavior

Video player should work without PiP support

### Actual behavior

Crashes after 0.2sec of playback

### Crash logs (or stack trace)

java. lang. IllegalStateException: setPictureInPictureParams: Device doesn't support picture-in-picture mode at android.os.Parcel.createException(Parcel.java: 1958) at android.os.Parcel. readException(Parcel.java: 1918) at android.os.Parcel. readException(Parcel.java: 1868)
at android.app.IActivityManager$Stub$Proxy.SetPictureInPictureParams(IActivityManager. java: 8997)
at android.app.Activity.setPictureInPictureParams(Activity.java:2197)
at com. flixclusive.mobile.MobileActivity$$ExternalSyntheticApiModelOutline0.m(Unknown Source:0) at com.flixclusive.core.ui.player.util.PlayerPiPHelperKt.updatePiPParams(PlayerPiPHelper.kt:96)
at com.flixclusive.core.ui.player.util.PlayerUiUtil$AudioFocusManager$2$1$1.invokeSuspend(PlayerUiUtil.kt:
it kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
t kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt: 108)
t androidx.compose.ui.platform.AndroidUiDispatcher.performTrampolineDispatch(AndroidUiDispatcher.android.

### App version

2.0.0

### Android version

7

### Device

Android Tv

### Other details

![Uploading IMG_3529.jpeg…]()

### Acknowledgements

- [X] I am ***fully confident*** that this issue is related solely to the app and not to any provider.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the **[pre-release version](https://github.com/rhenwinch/Flixclusive/releases/tag/pre-release)**.

**Comment by rhenwinch** [comment]
wait what... I thought I handled this properly.

alr, expect fix on next update. sorry for inconvenience :')

**Comment by freakynuell** [comment]
> wait what... I thought I handled this properly.
> 
> alr, expect fix on next update. sorry for inconvenience :')

thanks for acknowledging this early, I do have high hopes for this app and hope it is fixed soonest

**Comment by rhenwinch** [comment]
Seems like youre tryna use the mobile launcher on TV mode. I guess I'll just add an option to turn off PiP
