### ISSUE TITLE
Download Option

### ISSUE THREAD

**Issue by iamawanishmaurya** [rhenwinch/Flixclusive#120]
### Describe your suggested feature

Have you consider to add download option, if not please consider it and also add trakt to synchronized. Watched movies /series

**Comment by rhenwinch** [comment]
> download option

It's in the roadmap.

> please consider it and also add trakt to synchronized

also, in the roadmap.

Sorry for the late reply. Will close this now since there have been multiple feature requests with regards to the features you've listed here.
