### ISSUE TITLE
Add more providers

### ISSUE THREAD

**Issue by oathzed** [rhenwinch/Flixclusive#13]
Currently with the current consumet on a lot of shows there is no links.it would be a good idea to add more providers, maybe you can refer to these:

https://github.com/hexated/cloudstream-extensions-hexated/tree/master/SoraStream

**Comment by rhenwinch** [comment]
hey thanks! would def add this in addition to superstream. still kinda new with the scraping community.

**Comment by DarkCrypt** [comment]
I agree, SoraStream is the best source I've ever used so far.

**Comment by rhenwinch** [comment]
so... would it be better to go _full_ plugins/extensions system for providers? Just like like Tachi (RIP), CS3, etc. Would be nice if some devs would be glad to create their own providers

**Comment by oathzed** [comment]
> so... would it be better to go _full_ plugins/extensions system for providers? Just like like Tachi (RIP), CS3, etc. Would be nice if some devs would be glad to create their own providers

Yes it would be, that way you can keep them separate from the app. There are already lots of providers made, I guess it's up to you if you want to make them compatible with your app. Or yeah if you make any easy provider system, devs will make providers for it

**Comment by popcorn2024ok** [comment]
Hello friend please repositories flixclusive sources providers

**Comment by rhenwinch** [comment]
> Hello friend please repositories flixclusive news sources providers
> 
> news Providers please flixclusive soruces thanks you

could you recommend one? SoraStream is still  too big of a project to migrate on Flixclusive.

**Comment by oathzed** [comment]
> > Hello friend please repositories flixclusive news sources providers
> > news Providers please flixclusive soruces thanks you
> 
> could you recommend one? SoraStream is still too big of a project to migrate on Flixclusive.

Not that guy asking for providers but heres some that should be easier:

https://github.com/BeamlakAschalew/flixquest-api
https://github.com/cool-dev-guy/vidsrc-api

**Comment by rhenwinch** [comment]
thanks brobro

**Comment by oathzed** [comment]
> thanks brobro

❤️
I found something better:
https://github.com/sussy-code/providers
https://github.com/Aijazmakerb/vidsrc-api

Use these in tandem. This is reference with both:
https://github.com/ejatapibeda/JaMovies?tab=readme-ov-file

**Comment by rhenwinch** [comment]
I had some of the working providers on [Sudo-Flix](https://github.com/sussy-code/providers) already implemented [here](https://github.com/Flixclusive/flx-providers/tree/main/providers). Also, I might rename this to movie-web just out of respect 🫡.

Currently, I have NSBX + Ridomovies as a set. I noticed some of those included in that repository don't work anymore. I'll move on now on vidsrc if I don't find any working providers on sussy-code's repo anymore.

Thanks a lot!

**Comment by oathzed** [comment]
> I had some of the working providers on [Sudo-Flix](https://github.com/sussy-code/providers) already implemented [here](https://github.com/Flixclusive/flx-providers/tree/main/providers). Also, I might rename this to movie-web just out of respect 🫡.
> 
> Currently, I have NSBX + Ridomovies as a set. I noticed some of those included in that repository don't work anymore. I'll move on now on vidsrc if I don't find any working providers on sussy-code's repo anymore.
> 
> Thanks a lot!

Awesome, well done man. That sounds good, thank you!

**Comment by oathzed** [comment]
Hey man @rhenwinch , I have a question. How hard would it be to also make your provider system compatible with stremio add-ons? That way it could kind of lessen the stress of having to add more providers later since there will be other people maintaining ones already.

**Comment by rhenwinch** [comment]
> How hard would it be to also make your provider system compatible with stremio add-ons (just the streaming ones, not catalog ones)?

If we're gonna disregard the catalogues for now, then I think it would be an easy migrate. I like this idea.

I'm still figuring out how I could implement dynamic catalogues/categories on the home screen for the providers to have their own metadata collection of movies/tv shows. It's gonna be a hell of a refactor for the TMDB module of the app.

**Comment by oathzed** [comment]
> > How hard would it be to also make your provider system compatible with stremio add-ons (just the streaming ones, not catalog ones)?
> 
> If we're gonna disregard the catalogues for now, then I think it would be an easy migrate. I like this idea.
> 
> I'm still figuring out how I could implement dynamic catalogues/categories on the home screen for the providers to have their own metadata collection of movies/tv shows. It's gonna be a hell of a refactor for the TMDB module of the app.

Awesome. Yeh that would be pretty rad to have dynamic catalogues

**Comment by rhenwinch** [comment]
I can finally close this :')

all provider issues are migrated to respective repositories now

**Comment by oathzed** [comment]
> I can finally close this :')
> 
> all provider issues are migrated to respective repositories now

Much love. Well done on this :)
