### ISSUE TITLE
could not be  parsed at  index 0

### ISSUE THREAD

**Issue by Doctor2023** [rhenwinch/Flixclusive#18]
![Screenshot_20231206_180549](https://github.com/rhenwinch/Flixclusive/assets/129991276/ea451a57-8ec1-48dc-abb1-a6a8649cbb76)

I get this error I already installed version 1.3.0 apk
 in movies and series

**Comment by Doctor2023** [comment]
![Screenshot_20231206_181423](https://github.com/rhenwinch/Flixclusive/assets/129991276/ef1c0701-bdbd-4bce-9526-45839fa23ed5)
 
this error message appears

Top tv networks

Top movie Companies

**Comment by rhenwinch** [comment]
Looking at this now. New verbosed loggers are really coming in handy. Thanks!

**Comment by Doctor2023** [comment]
> I've finally reproduced the error. It seems like it happens due to the system language issues. Expect a fix soon

Ok friends thanks you

We just have to wait to find the solution to the problem

**Comment by Doctor2023** [comment]
> I've finally reproduced the error. It seems like it happens due to the system language issues. Expect a fix soon

fix soon

**Comment by rhenwinch** [comment]
Uploaded the latest patch. Can you try it now?

**Comment by Doctor2023** [comment]
> Uploaded the latest patch. Can you try it now?

Ok friend thanks you

**Comment by rhenwinch** [comment]
closing this for now, if its been solved. reopen, if not.
