### ISSUE TITLE
Clean Home UI 

### ISSUE THREAD

**Issue by MrConqueror** [rhenwinch/Flixclusive#2]
this app is so Cool but i have one suggestion you could remove the movie title since the title of the movie is already in the poster

**Comment by rhenwinch** [comment]
Thanks for the feedback and support! I've considered your suggestion and completely removed the unnecessary content on the home screen. Feel free to give more UI/UX feedbacks.

**Comment by MrConqueror** [comment]
> Thanks for the feedback and support! I've considered your suggestion and completely removed the unnecessary content on the home screen. Feel free to give more UI/UX feedbacks.

Nice really appreciate your hard work bro, anyway are you planning to add cast of characters of the movie and when you tap the profile you'll see their bio and movie/tvshow they are appeared. just like Letterboxd. disregard this if it's impossible to do.

**Comment by rhenwinch** [comment]
> are you planning to add cast of characters of the movie and when you tap the profile you'll see their bio and movie/tvshow they are appeared.

I will for sure consider adding this in the future, for now my current goal is to achieve offline watching and some minor UI changes get rid of titles on Film cards (bc I realized I forgot to remove it completely on the new update).

ps: I considered adding this feature before but I couldn't figure out where to put the 'other movie/tvshow infos' like casts, production, etc. on the UI. I was afraid to make the information too overwhelming for the user.

**Comment by DarkCrypt** [comment]
> remove the movie title since the title of the movie is already in the poster

Some users like the titles and some don't. This could be a toggle option within Settings.
