### ISSUE TITLE
Unable to update it to 1.3.2 


### ISSUE THREAD

**Issue by JinDevil21** [rhenwinch/Flixclusive#21]
I updated it to 1.3.2 through app and through GitHub release too.
But it is still on 1.3.1 and asking to update it to 1.3.2 everytime I open the app even tho  I tried installing it many times 

And a suggestion add a check box there of not to show it again.

**Comment by DarkCrypt** [comment]
The app version code didn't get changed from v1.3.1 to v1.3.2. The continuous updater will go away after rhenwinch fixes this.

**Comment by rhenwinch** [comment]
noob mistake, forgot to update the version. can yall try now so we could close this. also:

> And a suggestion add a check box there of not to show it again.

may i ask if u could open a new issue for this? thanks!

**Comment by DarkCrypt** [comment]
No worries, all part of learning.

Just updated with in-app updater without issue. App version is correct.

**Comment by DarkCrypt** [comment]
Can't update stable 1.3.2 -> 1.4.0 with in-app updater. Says version is already up to date.

**Comment by rhenwinch** [comment]
> Can't update stable 1.3.2 -> 1.4.0 with in-app updater. Says version is already up to date.

Hey, its because its still on pre-release. Ill put an option to opt in on prereleases

**Comment by DarkCrypt** [comment]
Understood.
