### ISSUE TITLE
Default audio language track

### ISSUE THREAD

**Issue by oathzed** [rhenwinch/Flixclusive#22]
Would be nice to have an option for us to set our default audio language track in settings. I've been opening up a lot of movies lately and they start as playing in Hindi

Cheers!

**Comment by rhenwinch** [comment]
update on this issue: I automated the audio selection based on the show's/movie's original language (i.e., animes gets japanese audio automatically). I've soon to yet add this audio language option.

Also, may I know what specific movie you are watching so I could check it on my end before releasing the new release?

**Comment by oathzed** [comment]
> update on this issue: I automated the audio selection based on the show's/movie's original language (i.e., animes gets japanese audio automatically). I've soon to yet add this audio language option.
> 
> Also, may I know what specific movie you are watching so I could check it on my end before releasing the new release?

Awesome, thanks man :).

Krampus 2015, defaults as hindi
