### ISSUE TITLE
Some video players bugs 

### ISSUE THREAD

**Issue by JinDevil21** [rhenwinch/Flixclusive#26]
Subs alignment is not proper with different screen size 

![Screenshot_20231210-141819_1.jpg](https://github.com/rhenwinch/Flixclusive/assets/147237329/7d1fcd98-8ff9-4d56-a3a2-04985291687b)

Also the bottom button (tabs, home, back buttons) are not hiding

**Comment by rhenwinch** [comment]
May I know what device youre using and SDK/Android version?

Also, sorry about the subtitles. It was meant to only support .VTT files but .SRT was introduced after the addition of SuperStream.

**Comment by JinDevil21** [comment]
![Screenshot_20231210-144034.jpg](https://github.com/rhenwinch/Flixclusive/assets/147237329/27fe9bb4-7c55-452b-8990-0fcde2f02413)
