### ISSUE TITLE
Bug on the new version 

### ISSUE THREAD

**Issue by EinsteinOfTech** [rhenwinch/Flixclusive#31]
![Screenshot_20231210-131215_Flixclusive](https://github.com/rhenwinch/Flixclusive/assets/106039148/5d6cacb8-2a4f-4973-9a48-a3e2195a5897)

**Comment by rhenwinch** [comment]
Godzilla Minus One is, unfortunately, not yet available on any of the providers the app currently has. I'm closing this for now.

**Comment by rhenwinch** [comment]
but does this happen on other movie/shows?

**Comment by rhenwinch** [comment]
closing this as this could be considered as a duplicate of #13
