### ISSUE TITLE
Subtitles 

### ISSUE THREAD

**Issue by WiseMikeyK** [rhenwinch/Flixclusive#35]
I noticed the subtitles switch is stuck on is there anywhere to fix this? Thank you in advance.

**Comment by oathzed** [comment]
Duplicate of #23

**Comment by rhenwinch** [comment]
Duplicate of #23 

this has been fixed now for the next coming patch.

**Comment by rhenwinch** [comment]
this has been fixed now for the next coming patch. expect it soon !
