### ISSUE TITLE
Crash on Nvidia Shield

### ISSUE THREAD

**Issue by naudski** [rhenwinch/Flixclusive#36]
Hi!

Very nice app!!
I installed it on my Nvidia Shield, but whenever I open a show or movie it crashes immediately. And then it restarts in the mobile version.

**Comment by rhenwinch** [comment]
is this using the android TV intreface? if so, then unfortunately the interface is not ready yet. im still pushing its development for its final release.

**Comment by naudski** [comment]
Yes it is. I wasn't aware of it still being in development, sorry.
App looks great though!!
