### ISSUE TITLE
Problem - EDIT: Player Enhancements

### ISSUE THREAD

**Issue by Blitz077** [rhenwinch/Flixclusive#37]
Why when i go out of the app while a video is playing it has to reload again once reopened and also can you make the video bar has time spent not time until it ends and a limit for buffering with options and also make us able to change the bar color and make the episode list horizontal not vertical . Wow thats a lot lol

**Comment by rhenwinch** [comment]
> Why when i go out of the app while a video is playing it has to reload again once reopened

The video player - Media3 (aka ExoPlayer) - is [releasing all the resources](https://developer.android.com/guide/topics/media/exoplayer/hello-world#release-player) it recently used causing the player to reload the source again to fetch the video you're watching.

If I disable this feature, this could probably mean that it could hog or leak some of the phone's memory if ever you forget to force close or remove the app from the task manager/recents list.

though, we could add another settings option for this.

> can you make the video bar has time spent not time until it ends

already added this one on the new upcoming update!

> a limit for buffering with options

lastly, may I ask if u could elaborate more about this feature?

**Comment by rhenwinch** [comment]
> make the episode list horizontal not vertical

I made big changes to the player ui btw. including this one. here's the sample preview:
![new episodes list layout](https://github.com/rhenwinch/Flixclusive/assets/52451354/3744debc-a31a-425d-a3f6-45202da71bfe)

**Comment by rhenwinch** [comment]
lastly, could u pls edit the title to be more specific about the issue. big thanks 💯

**Comment by Blitz077** [comment]
If by memory you mean ram then dont worry i have 8 gb and for the buffering i mean like it buffers for a certain time ahead from the moment youre watching i want us to have the ability to control the time it can buffer ahead so if per say it buffers a full minute ahead and then i go back like 5 secs it will do the buffering again and consume more internet

**Comment by Blitz077** [comment]
> lastly, could u pls edit the title to be more specific about the issue. big thanks 💯

What should it be we discussed a lot of stuff 😂

**Comment by rhenwinch** [comment]
> If by memory you mean ram then dont worry i have 8 gb and for the buffering i mean like it buffers for a certain time ahead from the moment youre watching i want us to have the ability to control the time it can buffer ahead so if per say it buffers a full minute ahead and then i go back like 5 secs it will do the buffering again and consume more internet

Ahh I see. Adding this as a feature for the next update since the next update has been all about the player
