### ISSUE TITLE
Indian Content Providers 

### ISSUE THREAD

**Issue by stingyman12** [rhenwinch/Flixclusive#38]
Could you please consider adding the following websites to the list of providers for this app?

1. [iBomma]( https://dell.ibomma.pw/telugu-movies/ ): This site offers content in the Telugu language from India.
2. [MovierulzHD]( https://movierulzhd.codes/): This website features content in all Indian languages.

Thank you for your consideration.

**Comment by rhenwinch** [comment]
sure !

**Comment by safdar9633** [comment]
Please this would  be the best thing ever!!!

**Comment by Parasgaming122** [comment]
Pls add 😊

**Comment by popcorn2024ok** [comment]
![IMG_0991](https://github.com/rhenwinch/Flixclusive/assets/165403113/5eeac0a7-0339-4db3-b961-6ec0ffe07364)

I get this error and problem in the Android TV and Android mobile versions. Please add more providers for Flixclusive, thanks. In English and Latin Spanish

**Comment by Doctor2023** [comment]
![Screenshot_20240608_133400_Flixclusive Beta](https://github.com/rhenwinch/Flixclusive/assets/129991276/eeca706f-708e-4d9c-aa4d-8516ec27beb4)

FlixHQ provider is not working properly

**Comment by rhenwinch** [comment]
> FlixHQ provider is not working properly

Yeah. They changed it again, sigh

**Comment by Doctor2023** [comment]
![Screenshot_20240608_133727_Flixclusive Beta](https://github.com/rhenwinch/Flixclusive/assets/129991276/b8f45931-628c-4803-992b-4a8a89ed21de)

Sudo-Flix
SuperStream 

Also these providers do not work on some movies and series like FlixHQ provider

**Comment by rhenwinch** [comment]
@Doctor2023 will be posting updated commits soon for FlixHQ. but please open up a new issue on this [repo](https://github.com/Flixclusive/flx-providers)

Thanks for the heads up brother!

**Comment by Doctor2023** [comment]
> ![IMG_0991](https://private-user-images.githubusercontent.com/165403113/337870393-5eeac0a7-0339-4db3-b961-6ec0ffe07364.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4NDc0MDgsIm5iZiI6MTcxNzg0NzEwOCwicGF0aCI6Ii8xNjU0MDMxMTMvMzM3ODcwMzkzLTVlZWFjMGE3LTAzMzktNGRiMy1iOTYxLTZlYzBmZmUwNzM2NC5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDhUMTE0NTA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWQ1NTc0ZjYwNWFkYzcwYTIyMjk0OTBkMTBhMTYyN2U4ODI2NGEwZTZiYWMzYTQ3MjE4MTYwZWJmODdkMjZlNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.lUEf2tjS6ltig-g6no6K6Qd6m4BotRXzrDgenfXYMuU)
> 
> I get this error and problem in the Android TV and Android mobile versions. Please add more providers for Flixclusive, thanks. In English and Latin Spanish

The same happens to me friend

**Comment by popcorn2024ok** [comment]
> > ![IMG_0991](https://private-user-images.githubusercontent.com/165403113/337870393-5eeac0a7-0339-4db3-b961-6ec0ffe07364.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4NDc0MDgsIm5iZiI6MTcxNzg0NzEwOCwicGF0aCI6Ii8xNjU0MDMxMTMvMzM3ODcwMzkzLTVlZWFjMGE3LTAzMzktNGRiMy1iOTYxLTZlYzBmZmUwNzM2NC5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDhUMTE0NTA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWQ1NTc0ZjYwNWFkYzcwYTIyMjk0OTBkMTBhMTYyN2U4ODI2NGEwZTZiYWMzYTQ3MjE4MTYwZWJmODdkMjZlNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.lUEf2tjS6ltig-g6no6K6Qd6m4BotRXzrDgenfXYMuU)
> > I get this error and problem in the Android TV and Android mobile versions. Please add more providers for Flixclusive, thanks. In English and Latin Spanish
> 
> The same happens to me friend



> > ![IMG_0991](https://private-user-images.githubusercontent.com/165403113/337870393-5eeac0a7-0339-4db3-b961-6ec0ffe07364.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4NDc0MDgsIm5iZiI6MTcxNzg0NzEwOCwicGF0aCI6Ii8xNjU0MDMxMTMvMzM3ODcwMzkzLTVlZWFjMGE3LTAzMzktNGRiMy1iOTYxLTZlYzBmZmUwNzM2NC5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDhUMTE0NTA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWQ1NTc0ZjYwNWFkYzcwYTIyMjk0OTBkMTBhMTYyN2U4ODI2NGEwZTZiYWMzYTQ3MjE4MTYwZWJmODdkMjZlNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.lUEf2tjS6ltig-g6no6K6Qd6m4BotRXzrDgenfXYMuU)
> > I get this error and problem in the Android TV and Android mobile versions. Please add more providers for Flixclusive, thanks. In English and Latin Spanish
> 
> The same happens to me friend

Ok, I understand you, we have the same problem.

**Comment by Doctor2023** [comment]
@rhenwinch

**Comment by rhenwinch** [comment]
That error is completely another issue #10 and not related to this issue. Please refer to that

**Comment by popcorn2024ok** [comment]
![Screenshot_20240608_174235_Flixclusive Beta](https://github.com/rhenwinch/Flixclusive/assets/165403113/66cad805-bf32-49a4-9c35-4c058692e2e8)

Provider stremio problem  errors  app Flixclusive

**Comment by Doctor2023** [comment]
> ![Screenshot_20240608_174235_Flixclusive Beta](https://private-user-images.githubusercontent.com/165403113/337901120-66cad805-bf32-49a4-9c35-4c058692e2e8.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4NjM4MjcsIm5iZiI6MTcxNzg2MzUyNywicGF0aCI6Ii8xNjU0MDMxMTMvMzM3OTAxMTIwLTY2Y2FkODA1LWJmMzItNDlhNC05YzM1LTRjMDU4NjkyZTJlOC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwOFQxNjE4NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYThkN2FiODgzMGFhYTI3YmE4OWZmMTY2YTQzZjhkZWMyNGZmZWIyOGUxYjY4NTBlYzExMjZjYmMyZjc4NjJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1lMykJB0d_xD_5A6G-eqYc56Grpz9ucRh_l1ky1fK3I)
> 

> Provider stremio problem errors app Flixclusive


![Screenshot_20240608_181826_Flixclusive Beta](https://github.com/rhenwinch/Flixclusive/assets/129991276/6fec188d-6005-4dcf-917e-929f1b3f63b3)

**Comment by Doctor2023** [comment]
> > ![Screenshot_20240608_174235_Flixclusive Beta](https://private-user-images.githubusercontent.com/165403113/337901120-66cad805-bf32-49a4-9c35-4c058692e2e8.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4NjM4MjcsIm5iZiI6MTcxNzg2MzUyNywicGF0aCI6Ii8xNjU0MDMxMTMvMzM3OTAxMTIwLTY2Y2FkODA1LWJmMzItNDlhNC05YzM1LTRjMDU4NjkyZTJlOC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwOFQxNjE4NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYThkN2FiODgzMGFhYTI3YmE4OWZmMTY2YTQzZjhkZWMyNGZmZWIyOGUxYjY4NTBlYzExMjZjYmMyZjc4NjJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1lMykJB0d_xD_5A6G-eqYc56Grpz9ucRh_l1ky1fK3I)
> 
> > Provider stremio problem errors app Flixclusive
>

**Comment by Doctor2023** [comment]
![Screenshot_20240608_181826_Flixclusive Beta](https://github.com/rhenwinch/Flixclusive/assets/129991276/222c5487-bda4-464b-8b35-a7af53f9b0e0)
 
I can't add stremio addons

**Comment by Doctor2023** [comment]
> ![Screenshot_20240608_174235_Flixclusive Beta](https://private-user-images.githubusercontent.com/165403113/337901120-66cad805-bf32-49a4-9c35-4c058692e2e8.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4NjQ4NzQsIm5iZiI6MTcxNzg2NDU3NCwicGF0aCI6Ii8xNjU0MDMxMTMvMzM3OTAxMTIwLTY2Y2FkODA1LWJmMzItNDlhNC05YzM1LTRjMDU4NjkyZTJlOC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwOFQxNjM2MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZWFmMjNjYjg1ZGNkNWRmYTIzMDk3N2IyMTM2NWJjNTVjNjU3YTk5YmQ1NGYyZTE4ZTlkZDA1NDE5MmRjMmE5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mdxSaMJEKfNO4ZDPZUc77znKHln5m2ZU-QShZ1T_kiM)
> 
> Provider stremio problem errors app Flixclusive version beta stremio provider

**Comment by rhenwinch** [comment]
@popcorn2024ok @Doctor2023 can you restart the app and let it auto-update Stremio. The issue might be fixed now.

If there are any more **provider issues**, please don't clog the thread up and open a new issue on this repository: https://github.com/Flixclusive/flx-providers

Thanks!

**Comment by popcorn2024ok** [comment]
![Screenshot_20240608_190211_Flixclusive Beta](https://github.com/rhenwinch/Flixclusive/assets/165403113/d29f9a27-7f1a-4a8a-bf1a-4726324189e0)

The message appeared again trying to put the stremio addons, I already put restart

**Comment by popcorn2024ok** [comment]
![2024_06_08_19 24 08](https://github.com/rhenwinch/Flixclusive/assets/165403113/72ffeb93-e522-4d1e-9ecb-84c3407c5350)

I don't get the Stremio video servers when I put on a movie or series app Flixclusive app

**Comment by Doctor2023** [comment]
![Screenshot_20240608_193352_Flixclusive Beta](https://github.com/rhenwinch/Flixclusive/assets/129991276/f5a15081-136d-4cdb-a691-06751262c44b)

provider FlixHQ is under maintenance
on Flixclusive

**Comment by Doctor2023** [comment]
Hello @rhenwinch

**Comment by Doctor2023** [comment]
![2024_06_09_01 26 41](https://github.com/rhenwinch/Flixclusive/assets/129991276/b3cb3be9-c0ff-4123-803a-2baaa2094d49)

I have problems with the stremio links the videos of all the movies and series do not appear

**Comment by oathzed** [comment]
> ![2024_06_09_01 26 41](https://private-user-images.githubusercontent.com/129991276/337936976-b3cb3be9-c0ff-4123-803a-2baaa2094d49.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4OTI4NTIsIm5iZiI6MTcxNzg5MjU1MiwicGF0aCI6Ii8xMjk5OTEyNzYvMzM3OTM2OTc2LWIzY2IzYmU5LWMwZmYtNDEyMy04MDNhLTJiYWFhMjA5NGQ0OS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwOVQwMDIyMzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYjY2YThkZGUzMjk5NzViNjU0NWY3MWRiMDdmNGQzMGUwY2E4YTNkZTVhMTM1NTg5NDEyMDk2N2VkOGIxYTFmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yAe5RgSITSBGlfHQhPdJ60oeuA02dfBNI0rD_SteaYc)
> 
> I have problems with the stremio links the videos of all the movies and series do not appear
> 
> Stremio No links found

Did you say what stremio addon you're using?

**Comment by Doctor2023** [comment]
> > ![2024_06_09_01 26 41](https://private-user-images.githubusercontent.com/129991276/337936976-b3cb3be9-c0ff-4123-803a-2baaa2094d49.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4OTI4NTIsIm5iZiI6MTcxNzg5MjU1MiwicGF0aCI6Ii8xMjk5OTEyNzYvMzM3OTM2OTc2LWIzY2IzYmU5LWMwZmYtNDEyMy04MDNhLTJiYWFhMjA5NGQ0OS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwOVQwMDIyMzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYjY2YThkZGUzMjk5NzViNjU0NWY3MWRiMDdmNGQzMGUwY2E4YTNkZTVhMTM1NTg5NDEyMDk2N2VkOGIxYTFmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yAe5RgSITSBGlfHQhPdJ60oeuA02dfBNI0rD_SteaYc)
> > I have problems with the stremio links the videos of all the movies and series do not appear
> > Stremio No links found
> 
> Did you say what stremio addon you're using?

I'm using torrentio Annatar thepiratebay  jackettio peerflix

**Comment by rhenwinch** [comment]
You can't use torrent addons without a debrid subscription. Media3 doesn't have torrent support _yet_.

Try using other open-source addons that provide direct url of the shows/movies instead of just the info hash.

**Comment by rhenwinch** [comment]
Closing this as someone had recommended the same providers on the flx-providers repo
