### ISSUE TITLE
Latest build is crashing,not able to open

### ISSUE THREAD

**Issue by IndusAryan** [rhenwinch/Flixclusive#4]
error occurred,unable to initialize the app in 2nd build
os- A13
Redmi note 7
Elixir OS

**Comment by rhenwinch** [comment]
Hi! If you cloned the repository, may I ask if you already have [firebase remote config](https://firebase.google.com/docs/remote-config/get-started?platform=android) properly setup?

If yes, then may I ask if there are any stacktrace generated?

**Comment by rhenwinch** [comment]
Nice! Suggestion is noted. Thanks 😊
