### ISSUE TITLE
Please Version Android tv

### ISSUE THREAD

**Issue by Doctor2023** [rhenwinch/Flixclusive#42]
When will there be a version for Android TV and improvements and changes 2024 Flixclusive

**Comment by tikkamasalla** [comment]
Waiting on it too. The TV UI is great, just crashes whenever you try to play anything.

**Comment by rhenwinch** [comment]
might take a bit time still. sorry :/ just refer to this issue so we wont make duplicate ones when it comes to the android tv port. #19
