### ISSUE TITLE
"failed to extract, try again later"

### ISSUE THREAD

**Issue by MarshMeadow** [rhenwinch/Flixclusive#46]
### Steps to reproduce

go to a movie and try to play it it gives me an error: "failed to extract, try again later"

### Expected behavior

"failed to extract, try again later" it should be playing the film

### Actual behavior

"failed to extract, try again later"

### Crash logs (or stack trace)

"failed to extract, try again later"

### Flixclusive version

latest version

### Android version

android 12

### Device

Samsung galaxy s10 plus

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [X] I have updated the app to the **[latest version](https://github.com/rhenwinch/Flixclusive/releases/latest)**.

**Comment by rhenwinch** [comment]
FlixHQ provider problem. Its the only provider that has an embedded extractor.

Was it fixed eventually? It gets fixed at some point because key extraction is buggy sometimes

**Comment by rhenwinch** [comment]
I checked it on my end. The provider is working fine. Just buggy sometimes, I really can't do nothing about this one yet so closing this for now.

**Comment by rhenwinch** [comment]
They're outdated sadly. Superstream has been broken for awhile, while Lookmovie had api changes. Look at #13 for provider status changes.
