### ISSUE TITLE
Didn't even open 

### ISSUE THREAD

**Issue by Zaxx69** [rhenwinch/Flixclusive#5]
![Screenshot_2023-08-10-21-54-34-24_e8ccd80afe35f7798e3674be308ad800.jpg](https://github.com/rhenwinch/Flixclusive/assets/138523882/2738f32b-a983-4ae2-b62c-c83a0d291d1b)

I just installed the app and it showed this

**Comment by rhenwinch** [comment]
May I ask if it is still like this? This error might have something to do about internet connectivity to the config provider (firebase)

**Comment by Zaxx69** [comment]
It was ip issue, used vpn to fix it, sorry for the late reply

**Comment by rhenwinch** [comment]
I've now removed the dependency for Firebase Remote Config on [v1.2.0](https://github.com/rhenwinch/Flixclusive/releases/tag/v1.2.0). It was causing several initialization problems for some.
