### ISSUE TITLE
Make the app source more open source friendly

### ISSUE THREAD

**Issue by oathzed** [rhenwinch/Flixclusive#50]
### Describe your suggested feature

Would  be great if there was a quick start up guide on how to get the source code up and running through android studio and how to build the apk for testing purposes and edits.

cheers! :)

**Comment by rhenwinch** [comment]
idk if I resolved this issue now but for dev talks, the discord server would help

closing this. thanks man

**Comment by oathzed** [comment]
> idk if I resolved this issue now but for dev talks, the discord server would help
> 
> closing this. thanks man

I haven't had the time to take a look again but I will let you know through discord when I get the chance, thank you
