### ISSUE TITLE
Forced Notifications?

### ISSUE THREAD

**Issue by Uvdon** [rhenwinch/Flixclusive#51]
### Steps to reproduce

Explain. 

Someone who knows coding is more than welcome to also explain as I am no coder. 

### Expected behavior

Dev plz explain the reason behind you forcing users to turn in the app notifications? This is suspicious, respectfully. Also, the apps consumes way too much battery there is something going on here. I don't believe the source code is accurate on this app. Anyone who knows coding can also explain  

### Actual behavior

Ur forcing me to turn on notifications 

### Crash logs (or stack trace)

Don't know,

### Flixclusive version

Recent

### Android version

11

### Device

Pixel

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the **[latest version](https://github.com/rhenwinch/Flixclusive/releases/latest)**.

**Comment by rhenwinch** [comment]
Hey, I appreciate the concern.

> the reason behind you forcing users to turn in the app notifications

I have no ill intention or whatsoever on whoever tries to use the app. The notifications request is simply for the [independent updater service](https://github.com/rhenwinch/Flixclusive/blob/master/service/src/main/kotlin/com/flixclusive/service/update/util/NotificationExtensions.kt#L33) when it downloads the new apk update from the latest releases page.

> The apps consumes way too much battery there is something going on here.

Does this happen when the player is on? You're the first one to open up this issue.

> I don't believe the source code is accurate on this app. Anyone who knows coding can also explain

I recently added a [github-actions](https://github.com/rhenwinch/Flixclusive/blob/master/.github/workflows/Build.yml) that would automate the build releases of the app. This means that all releases _since_ the prereleases commits would be automated by github. This should serve as an evidence that the source code is _legitimate_.

To be more transparent, the current prerelease build will automatically send an error log if the app crashes on your end. It contains the following details: stacktrace and device info. 

**I still need to modify the splash screen of the app for first time users to notify them about the disclaimers and such about what the app will do.** 

Also, I have planned to add the option for user to opt-in on the automatic crash log sender feature.

If I have answered most of your questions, please close the issue. Thanks!

**Comment by Farid001979** [comment]
What about Android TV version ?

**Comment by rhenwinch** [comment]
> What about Android TV version ?

Are you talking about the (1) Android TV update or (2) the same issue but on Android TV?
- (1). Its UI is incomplete but the main core of watching shows/movies is okay. Also, its Compose TV is buggy asl I cant do nothing about that.
- (2). This repository only has one `.apk` file and it both contains the mobile and tv version of it. Its 2-in-1.

**Comment by Uvdon** [comment]
Thank u for the clarification. And yes, the app does consume a lot of battery then it needs too; I believe it has something to do with the ui. Plz note that my Device is red note 11 which has great battery life
