### ISSUE TITLE
Fix multiple back stack not working.

### ISSUE THREAD

**Issue by rhenwinch** [rhenwinch/Flixclusive#52]
Navigation screens don't clears their backstacks when navigating using bottombar.

**Comment by Doctor2023** [comment]
![Screenshot_20240222_182248_Flixclusive](https://github.com/rhenwinch/Flixclusive/assets/129991276/b166bb8a-711d-48b0-900a-607b3b697a9b)


I get this message in the flixclusive application I can t watch the movies and series

**Comment by rhenwinch** [comment]
@Doctor2023 Check #53

**Comment by Doctor2023** [comment]
> @Doctor2023 Check #54

ok friend thanks you
