### ISSUE TITLE
Can u add viewasian and kisskh extension too in this app so that all asian dramas can be watched cos some asian dramas r not working in this app

### ISSUE THREAD

**Issue by Aruraka** [rhenwinch/Flixclusive#57]
### Describe your suggested feature

Hii I wanna suggest u to implement an extension called kisskh and viewasian so that all asian dramas can be watched

**Comment by rhenwinch** [comment]
Hey,

This issue has been raised on the flx-providers repo. I'll close this and will update there instead.

https://github.com/Flixclusive/flx-providers/issues/7
