### ISSUE TITLE
Watchlist

### ISSUE THREAD

**Issue by Elhopper83** [rhenwinch/Flixclusive#58]
### Steps to reproduce

I wish the watchlist was formatted a bit better, it's a bit messy, I can't really explain it but I'll show you
![Screenshot_20240305-114724](https://github.com/rhenwinch/Flixclusive/assets/162350751/7faed929-bd06-4431-b875-23e784daeff7)
![Screenshot_20240305-114740](https://github.com/rhenwinch/Flixclusive/assets/162350751/5f6d4c2d-779d-47da-87bb-ddd47c94f03a)
![Screenshot_20240305-114748](https://github.com/rhenwinch/Flixclusive/assets/162350751/e9fcaee9-113c-41e8-95dd-a8548a6a6dbe)
![Screenshot_20240305-114753](https://github.com/rhenwinch/Flixclusive/assets/162350751/5d39e477-c73f-474d-83b1-ec9f230bbf98)

### Expected behavior

Make the watchlist so we can sort by most recent, so that way it'll be easier to categorize.

### Actual behavior

Basically the more you add, the more the watchlist is completely random, and it's kinda convoluted to me, 

### Flixclusive version

1.4.0-beta1

### Android version

Android 12

### Device

Blu M8l plus

### Other details

I wanted my watchlist to be:
Stranger Things
Wednesday
Star Wars 1-6
The Harry Potter films
The Batman films
And the MCU infinity saga

In that order

But as I added more movies as you can see it became something more like: A Star Wars movie here, some Batman movies there, Stranger Things there, another Star Wars movie here, etc.

I like things to be categorized and organized.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the **[latest version](https://github.com/rhenwinch/Flixclusive/releases/latest)**.

**Comment by rhenwinch** [comment]
Hi,

this has been fixed! though, some of your past watchlist might not get updated because my lazy ass didnt realize the watchlist items dont have a identifier for when they were added. thats why it doesn't sort out properly.

In regards to more filters, I'll postpone this feature and add them as backlogs for the future.
