### ISSUE TITLE
Navigation buttons don't disappear when trying to hide them

### ISSUE THREAD

**Issue by Uvdon** [rhenwinch/Flixclusive#6]
The 3 navigation buttons don't seem to disappear

**Comment by MrConqueror** [comment]
> The 3 navigation buttons don't seem to disappear

wdym? that's how it should be.

**Comment by Uvdon** [comment]
When streaming, the navigation buttons don't disappear. What do you mean that it should be like that, I don't get it because no player is like that and it's distraction

**Comment by MrConqueror** [comment]
![Screenshot_2023-08-17-12-19-50-786_com flixclusive](https://github.com/rhenwinch/Flixclusive/assets/102837820/2336ce66-b188-4351-8abf-ea8559147ad1)
Oh sorry I really thought you meant Homepage because i didn't have that kind of problem in player

**Comment by rhenwinch** [comment]
> When streaming, the navigation buttons don't disappear.

May I ask what device you are using? Also, a screenshot would be nice

**Comment by Uvdon** [comment]
Sorry for not being clear. Yes I'll send a screenshot. Also, I'm on android 11 Redmi note 11

**Comment by Uvdon** [comment]
![Screenshot_2023-08-17-00-15-40-139_com flixclusive](https://github.com/rhenwinch/Flixclusive/assets/141610471/1a19d4d4-1b49-4d81-949a-51a54e9f8da8)

**Comment by rhenwinch** [comment]
Will try to fix this on the next update. Thanks for the initiative!

**Comment by Uvdon** [comment]
I'm at work rn, when I get home I'll try thank you. Also, I have a small request for the next update; would you be able to add lookmovie provider. There is an app called "wiwi cinema" but they have too much advertising and it's closed source, however the quality of videos and sound too is crystal clear and is super fast. Thanks for your help.

**Comment by rhenwinch** [comment]
> I'm at work rn, when I get home I'll try thank you. Also, I have a small request for the next update; would you be able to add lookmovie provider. There is an app called "wiwi cinema" but they have too much advertising and it's closed source, however the quality of videos and sound too is crystal clear and is super fast. Thanks for your help.

Sure! May I ask if you have a legitimate link of their app? Reverse engineering it should not take time since it is an app.

**Comment by Uvdon** [comment]
Yes np. Here it is: 

https://cinema.wiwicenter.com/

Thank you ❤️ and if you can't do it or don't want to do it, I totally understand it's totally up to u no problem.

**Comment by Uvdon** [comment]
Thank u
Here is the link

:https://cinema.wiwicenter.com/

**Comment by Uvdon** [comment]
I also forgot to mention that I'm no programmer. But the only reason why I found out that this app (wiwi Cinema) uses lookmovie provider/website, is because it asks u for captcha every now and then.

Lookmovie website: 
https://lookmovie.foundation/

**Comment by Uvdon** [comment]
Just tested it. The navigation butt still do not disappear , however it don't matter because I have decided not to use the app as it consumes way too much battery on my phone. Thanks anyways. Thank u so much

**Comment by rhenwinch** [comment]
seems like this issue was caused by buggy WindowInsetsController code. Hoping the issue is fixed now on API 29 below.
