### ISSUE TITLE
Source

### ISSUE THREAD

**Issue by Blitz077** [rhenwinch/Flixclusive#60]
### Steps to reproduce

1_ Flixhq doesnt work anymore the server is down ,super stream stopped providing long time ago 
2_ the statments in the opening screen if i chose it once why does it popup every time 

### Expected behavior

Source to work 

### Actual behavior

Sources are outdated and dont work 

### Flixclusive version

1.4.0-1

### Android version

Android 13

### Device

Xaiomi 11T pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the **[latest version](https://github.com/rhenwinch/Flixclusive/releases/latest)**.

**Comment by rhenwinch** [comment]
Fixed now. SuperStream has no hope anymore; might just kill it soon
