### ISSUE TITLE
Reason for the Sudden Maintenance.

### ISSUE THREAD

**Issue by rhenwinch** [rhenwinch/Flixclusive#7]
### The Upcoming 1.2.0:
- I am currently embedding the [Consumet extractors/providers](https://github.com/consumet/consumet.ts) on the project for 'lowering-cost' purposes (might affect performance and player loading time). 
- Some minor UI changes on the video player;
- Android TV and Android Mobile multi-support;
- Improved "Home" screen with more-more-more-more recommendations!
- Currently planning to change the navigation graph and;
- Provide easier access to user's personal data/preferences.

Also, the maintenance may take a while because I'm gonna get real busy next week.

Apologies for the inconveniences and thanks for the consideration!

**Comment by Uvdon** [comment]
Can you please change the provider to lookmovies. It's so much faster and has almost anything you want to watch.

**Comment by rhenwinch** [comment]
> Can you please change the provider to lookmovies. It's so much faster and has almost anything you want to watch.

Hi! As of now, I have no time to reverse engineer to create a scraper for lookmovie. Tho, thanks for your suggestion; gonna try my best to note this if ever the app's current provider becomes unreliable.
