### ISSUE TITLE
Videos keep stop playing randomly 

### ISSUE THREAD

**Issue by Parasgaming122** [rhenwinch/Flixclusive#74]
### Steps to reproduce

![Screenshot_20240609-155050](https://github.com/rhenwinch/Flixclusive/assets/98590880/05b3075a-91c1-48d7-af58-bc23493fa83e)

![Screenshot_20240609-155122](https://github.com/rhenwinch/Flixclusive/assets/98590880/509ab62b-871e-4998-a43b-a70ac7d0172b)
I was watching the video for half hour suddenly stopped working. The gui was showing up but the error keep coming up then after a lot of tries it started working again for 10 mins now again same error and stop working again 
Server was super stream

### Expected behavior

Shouldn't stop randomly 

### Actual behavior

Stops randomly

### Flixclusive version

1.4.0 beta pre release 

### Android version

Android 9

### Device

Infinx smart 3 plus

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the **[latest version](https://github.com/rhenwinch/Flixclusive/releases/latest)**.

**Comment by rhenwinch** [comment]
Is this Sudo-Flix? Looks like a provider issue.

In media3 (the internal player of most video apps in android), 2004 means it's a _bad_ response from a provider link. It could be some link provided to you aren't working properly due to ISP block or any some sort of DDoS guard protection.

**Comment by Parasgaming122** [comment]
It's super stream

**Comment by rhenwinch** [comment]
> It's super stream

Ah, I will close this now since this is more of a provider issue. I really can't do nothing about it. If there are anymore issues about providers please open one here: https://github.com/Flixclusive/flx-providers/issues
