### ISSUE TITLE
None of the movies or shows are working

### ISSUE THREAD

**Issue by Ali-faraz-khan96** [rhenwinch/Flixclusive#75]
### Steps to reproduce

1. Open the app
2. Select anything shows or movies
3. Tap on watch now

### Expected behavior

The streaming should start
![Screenshot_20240613_031656_Flixclusive](https://github.com/rhenwinch/Flixclusive/assets/172549938/e390e465-2239-4fbc-8b77-82c7b1e732ab)

### Actual behavior

Error: "Im sorry, this is not yet watchable"

### Flixclusive version

1.4.0-beta1

### Android version

Android 13

### Device

Samsung Galaxy A32

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the **[latest version](https://github.com/rhenwinch/Flixclusive/releases/latest)**.

**Comment by rhenwinch** [comment]
Sorry for this. The current latest update does not have working providers.

To fix this, go and install the pre-release version (and turn on pre-release updates if you wish to do so). There, you now have the option to install providers. Until then, we can just cling on to this solution.

**Comment by Ali-faraz-khan96** [comment]
Okayy but can you help me and tell me where to get providers

**Comment by DarkCrypt** [comment]
> Okayy but can you help me and tell me where to get providers

You can use the built-in providers and/or install Stremio addons.

**Comment by Ali-faraz-khan96** [comment]
Alright thanks man. Love the app tho
