### ISSUE TITLE
Suddenly Close

### ISSUE THREAD

**Issue by MrConqueror** [rhenwinch/Flixclusive#8]
Thankyou for the latest update but the app suddenly Close I don't know why. i tried to open it again and choose a movie and the it closed again.

**Comment by rhenwinch** [comment]
oops. lemme look at it for abit

**Comment by MrConqueror** [comment]
> oops. lemme look at it for abit


https://github.com/rhenwinch/Flixclusive/assets/102837820/7261e863-9b36-49c2-9699-2e9ae120bb5f

**Comment by rhenwinch** [comment]
Seems like it only happens on TV Shows. This is definitely R8 issue.

**Comment by rhenwinch** [comment]
Issue is fixed now, thanks for the super early initiative! Feel free to list out more issues before v1.3.0
