### ISSUE TITLE
Stuck at loading animation 

### ISSUE THREAD

**Issue by basil222** [rhenwinch/Flixclusive#85]
### Steps to reproduce

After updating the app, it gets stuck at the loading animation everytime I open it 

### Expected behavior

App should open

### Actual behavior

App gets stuck at loading screen 

### Flixclusive version

1.4.0 pre relese 

### Android version

Android 14

### Device

Samsung s22

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the **[latest version](https://github.com/rhenwinch/Flixclusive/releases/latest)**.

**Comment by rhenwinch** [comment]
What stremio addons did you have before?

**Comment by rhenwinch** [comment]
What stremio addons did you have before?

Also happened to me too, still finding out where the problem is. Sorry brother
