### ISSUE TITLE
App - edit: Add backups of previous APK commits 

### ISSUE THREAD

**Issue by napacia** [rhenwinch/Flixclusive#87]
### Describe your suggested feature

(Updated my app cuz I just wanna see what's new :" ) I think it would be nice to still have previous versions of this app available for instances like this because the newly released version is kinda buggy and has minor issues. Thanks 🙏🏻

**Comment by rhenwinch** [comment]
Hi @napacia,

Thanks for the suggestion! Really sorry for the recent commits/pre-releases recently. I've been configuring the catalog system of the providers and it is currently a mess. Though, I had warned users when turning on pre-release updates that some commits/versions might be app breaking. 

Regarding your feature request, I love the idea of this. I will definitely make a new repository in @Flixclusive to save all the archived/backup apks there for previous versions. However, I might not be able to do this feature during this update. Would it be okay if I could postpone it for the next update? Say v2.1.0?

Again, sorry for the inconvenience.

**Comment by napacia** [comment]
> Would it be okay if I could postpone it for the next update? Say v2.1.0?

Yes, of course. I'll just wait for the update you r working on rn. Take your time and thank you for all the efforts you r putting in 🫂

**Comment by rhenwinch** [comment]
Hi

I have made an [archives branch](https://github.com/rhenwinch/Flixclusive/tree/archives). The CI should automatically upload all apks per pre-release commits. Thanks for this suggestion, really helpful!
