### ISSUE TITLE
Issues to fix before v1.3.0

### ISSUE THREAD

**Issue by rhenwinch** [rhenwinch/Flixclusive#9]
Known issues encountered (this will be updated regularly):
- Double-tap gesture on player does not work after returning from the minimized state app.
- Copy button on Preferences does not return the app link instead it returns `URL_TEST` lol
- The app does not save state of each episodes watched if you let it auto-play.

please bare with me as the current version is not yet ready and suitable for release. 

EDIT (09/22/23): UpCloud server does not work currently, you can change the server preference in the settings to VidCloud instead. 
EDIT (10/03/23): All UpCloud issues seems to be fine now.

EDIT (01/11/23): Hi! Really sorry about the lack of updates. Kinda just busy on other personal stuff, I will try to backtrack once I get a full time to handle all these enhancements and bugs. Thanks for the consideration <3

**Comment by DarkCrypt** [comment]
_Issues - v1.2.1_

Posters
- Not sized correctly, zoomed in too far.

Search
- Clear text button (X) resets search query but doesn't clear the text.
___
_Enhancements_

Video Player
- Change screen size (Ex. Fit to screen, Full, Fill, Zoom, Stretch).

Settings
- Add global video quality preference.
- Add toggle switch for poster titles.

In-App Updater
- Independent app updater.

**Comment by Doctor2023** [comment]
Hello friend Please apk v1.3.0 thanks you

**Comment by DarkCrypt** [comment]
V1.3.0 is a great improvement and I'm excited for future developments!

Thank you for adding these features and for all your continued work on this project.

I also thank you for the recognition you expressed on the releases page. I appreciate the love and respect. May God bless you forever friend!
