### ISSUE TITLE
Sort by release date

### ISSUE THREAD

**Issue by aneesh1122** [rhenwinch/Flixclusive#95]
### Describe your suggested feature

Please add an option to sort search results by 'release date'

**Comment by Doctor2023** [comment]
Hello friend Open more providers for the flixclusive application friend  @rhenwinch

**Comment by rhenwinch** [comment]
> Hello friend Open more providers for the flixclusive application friend @rhenwinch

Wrong thread to post this. Look at [flx-providers](https://github.com/Flixclusive/flx-providers) repository

**Comment by rhenwinch** [comment]
Hey @aneesh1122,

Sorry for the late reply, I just looked at TMDB's search query endpoint and unfortunately they don't support sorting by release dates. Implementing this logic manually thru the app is _not ideal_, tbh. So no plans for this for now, sorry.

**Comment by aneesh1122** [comment]
> Hey @aneesh1122,
> 
> Sorry for the late reply, I just looked at TMDB's search query endpoint and unfortunately they don't support sorting by release dates. Implementing this logic manually thru the app is _not ideal_, tbh. So no plans for this for now, sorry.

I just saw in the changelog that you've added the option to sort by release date? 😅

**Comment by rhenwinch** [comment]
Ah, its for the collections of movies. not the search results

**Comment by aneesh1122** [comment]
> Ah, its for the collections of movies. not the search results. Collections dont go over 20+ movies per query so theyre easy to sort by date

Does TMBD let you categorise between movies and series? Search results include both.

**Comment by rhenwinch** [comment]
Yep, we used to have that option but I've recently remove it. Still looking for a way to include search filters for custom catalogs. Might take time

**Comment by rhenwinch** [comment]
would you mind creating an issue again on adding a **search filter** instead of just sorting by release date? I need the search screen to be fully flexible for other providers' search method

**Comment by aneesh1122** [comment]
> Yep, we used to have that option but I've recently remove it. Still looking for a way to include search filters for custom catalogs. Might take time

Alright man. Perfection takes time so pls take all the time you want.

**Comment by aneesh1122** [comment]
> would you mind creating an issue again on adding a **search filters option** instead of just sorting by release date? I need the search screen to be fully flexible for other providers' search method

Sure
