### ISSUE TITLE
Playback Error

### ISSUE THREAD

**Issue by napacia** [rhenwinch/Flixclusive#96]
### Steps to reproduce

I've recently encountered a new issue. This problem occurs with some movies I've tried opening in 4K (mostly) and 1080p resolutions.
![Screenshot_20240703-033937](https://github.com/rhenwinch/Flixclusive/assets/155670053/e0f4402c-51c5-40b0-b7ca-06b05e262655)

### Expected behavior

For all the links/sources to play 

### Actual behavior

Going back on the screenshot I attached, this is what I got. 

### Flixclusive version

2.0.0

### Android version

Android 11

### Device

Realme C21Y

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the **[latest version](https://github.com/rhenwinch/Flixclusive/releases/latest)**.

**Comment by rhenwinch** [comment]
Hi,

This is device issue. It's probably that your CPU does not have the proper capabilities to render the following stream.

**Comment by napacia** [comment]
Thank you for responding :))

**Comment by rhenwinch** [comment]
hey again @napacia,

I just pushed the new update. It should lessen those errors now and play the stream regardless of your device's hardware capabilities. Tho, it comes at a cost of the slow performance and more power usage.
